RobotConfig:
  robot_name: "hhfc"
  type: "mujoco"
  joint_size: 20
  motor_size: 20
  joint_names: &joint_names
    - "l_hip_y"
    - "l_hip_r"
    - "l_hip_p"
    - "l_knee"
    - "l_ankle_p"
    - "l_ankle_r"
    - "r_hip_y"
    - "r_hip_r"
    - "r_hip_p"
    - "r_knee"
    - "r_ankle_p"
    - "r_ankle_r"
    - "l_shoulder_p"
    - "l_shoulder_r"
    - "l_shoulder_y"
    - "l_elbow_p"
    - "r_shoulder_p"
    - "r_shoulder_r"
    - "r_shoulder_y"
    - "r_elbow_p"
  motor_names: *joint_names

  motor_direction:
    l_hip_y: 1
    l_hip_r: 1
    l_hip_p: 1
    l_knee: 1
    l_ankle_p: 1
    l_ankle_r: 1
    r_hip_y: 1
    r_hip_r: 1
    r_hip_p: 1
    r_knee: 1
    r_ankle_p: 1
    r_ankle_r: 1
    l_shoulder_p: 1
    l_shoulder_r: 1
    l_shoulder_y: 1
    l_elbow_p: 1
    r_shoulder_p: 1
    r_shoulder_r: 1
    r_shoulder_y: 1
    r_elbow_p: 1

  observer:
    log_data: true
    log_dir: "/home/jason/bitbot-ovinf/log/extra"
    motor_pos_filter:
      # type: "None"
      type: "PassThrough"
      lower_bound: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                    -3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                    -3.14, -3.14, -3.14, -3.14,
                    -3.14, -3.14, -3.14, -3.14,]
      upper_bound: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                    3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                    3.14, 3.14, 3.14, 3.14, 
                    3.14, 3.14, 3.14, 3.14,] 
    motor_vel_filter:
      # type: "None"
      # type: "PassThrough"
      type: "Mean"
      history_length: 3
      lower_bound: [-50.0, -50.0, -50.0, -50.0, -50.0, -50.0,
                    -50.0, -50.0, -50.0, -50.0, -50.0, -50.0,
                    -50.0, -50.0, -50.0, -50.0,
                    -50.0, -50.0, -50.0, -50.0,]
      upper_bound: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0,
                    50.0, 50.0, 50.0, 50.0, 50.0, 50.0,
                    50.0, 50.0, 50.0, 50.0,
                    50.0, 50.0, 50.0, 50.0,] 
    ang_vel_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    acc_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    euler_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]

  executor:
    torque_limit:  # Nm
      l_hip_p: 500.0
      l_hip_r: 500.0
      l_hip_y: 500.0
      l_knee: 500.0
      l_ankle_p: 500.0
      l_ankle_r: 500.0
      r_hip_p: 500.0
      r_hip_r: 500.0
      r_hip_y: 500.0
      r_knee: 500.0
      r_ankle_p: 500.0
      r_ankle_r: 500.0
      l_shoulder_p: 500.0
      l_shoulder_r: 500.0
      l_shoulder_y: 500.0
      l_elbow_p: 500.0
      r_shoulder_p: 500.0
      r_shoulder_r: 500.0
      r_shoulder_y: 500.0
      r_elbow_p: 500.0
    motor_upper_limit:  # rad
      l_hip_p: 3.14
      l_hip_r: 3.14 
      l_hip_y: 3.14 
      l_knee: 3.14 
      l_ankle_p: 3.14 
      l_ankle_r:  3.14
      r_hip_p: 3.14
      r_hip_r: 3.14
      r_hip_y: 3.14
      r_knee: 3.14
      r_ankle_p: 3.14
      r_ankle_r: 3.14
      l_shoulder_p: 3.14
      l_shoulder_r: 3.14
      l_shoulder_y: 3.14
      l_elbow_p: 3.14
      r_shoulder_p: 3.14
      r_shoulder_r: 3.14
      r_shoulder_y: 3.14
      r_elbow_p: 3.14

    motor_lower_limit:  # rad
      l_hip_p: -3.14
      l_hip_r: -3.14
      l_hip_y: -3.14
      l_knee: -3.14
      l_ankle_p: -3.14
      l_ankle_r: -3.14
      r_hip_p: -3.14
      r_hip_r: -3.14
      r_hip_y: -3.14
      r_knee: -3.14
      r_ankle_p: -3.14
      r_ankle_r: -3.14
      l_shoulder_p: -3.14
      l_shoulder_r: -3.14
      l_shoulder_y: -3.14
      l_elbow_p: -3.14
      r_shoulder_p: -3.14
      r_shoulder_r: -3.14
      r_shoulder_y: -3.14
      r_elbow_p: -3.14

  init_pos:
    duration: 1.5
    init_position: &defult_init_pos
      l_hip_y: 0.0
      l_hip_r: 0.0
      l_hip_p: -0.3
      l_knee: 0.6
      l_ankle_p: -0.3
      l_ankle_r: 0.0
      r_hip_y: 0.0
      r_hip_r: 0.0
      r_hip_p: -0.3
      r_knee: 0.6
      r_ankle_p: -0.3
      r_ankle_r: 0.0
      l_shoulder_p: 0.0
      l_shoulder_r: 0.0
      l_shoulder_y: 0.0
      l_elbow_p: 0.0
      r_shoulder_p: 0.0
      r_shoulder_r: 0.0
      r_shoulder_y: 0.0
      r_elbow_p: 0.0

    p_gains: &default_p_gains
      l_hip_y: 150.0
      l_hip_r: 200.0
      l_hip_p: 150.0
      l_knee: 200.0
      l_ankle_p: 40.0
      l_ankle_r: 40.0
      r_hip_y: 150.0
      r_hip_r: 200.0
      r_hip_p: 150.0
      r_knee: 200.0
      r_ankle_p: 40.0
      r_ankle_r: 40.0
      l_shoulder_p: 200
      l_shoulder_r: 200
      l_shoulder_y: 200
      l_elbow_p: 200
      r_shoulder_p: 200
      r_shoulder_r: 200
      r_shoulder_y: 200
      r_elbow_p: 200

    d_gains: &default_d_gains
      l_hip_y: 2.0
      l_hip_r: 3.0
      l_hip_p: 2.0
      l_knee: 3.0
      l_ankle_p: 2.0
      l_ankle_r: 2.0
      r_hip_y: 2.0
      r_hip_r: 3.0
      r_hip_p: 2.0
      r_knee: 3.0
      r_ankle_p: 2.0
      r_ankle_r: 2.0
      l_shoulder_p: 1
      l_shoulder_r: 1
      l_shoulder_y: 1
      l_elbow_p: 1
      r_shoulder_p: 1
      r_shoulder_r: 1
      r_shoulder_y: 1
      r_elbow_p: 1

  zero_pos:
    duration: 1.0
    init_position: *defult_init_pos
    p_gains: *default_p_gains
    d_gains: *default_d_gains

  policy_humanoid:
    p_gains: *default_p_gains
    d_gains: *default_d_gains
    decimation: 10

    inference:
      policy_type: "Humanoid"
      model_path: "/home/jason/bitbot-ovinf/checkpoint/fc2/5k.onnx"

      log_data: true
      log_dir: "/home/jason/bitbot-ovinf/log/policy"

      device: "CPU"
      cycle_time: 0.70
      single_obs_size: 47
      obs_buffer_size: 15
      action_size: 12
      action_scale: 0.5
      obs_scales:
        ang_vel: 1.0
        lin_vel: 2.0
        command: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        proj_gravity: 1.0
      clip_action: 18.0
      realtime: false

      policy_joint_names:
        - "l_hip_y"
        - "l_hip_r"
        - "l_hip_p"
        - "l_knee"
        - "l_ankle_p"
        - "l_ankle_r"
        - "r_hip_y"
        - "r_hip_r"
        - "r_hip_p"
        - "r_knee"
        - "r_ankle_p"
        - "r_ankle_r"

      policy_default_position:
        l_hip_y: 0.0
        l_hip_r: 0.0
        l_hip_p: -0.3
        l_knee: 0.6
        l_ankle_p: -0.3
        l_ankle_r: 0.0
        r_hip_y: 0.0
        r_hip_r: 0.0
        r_hip_p: -0.3
        r_knee: 0.6
        r_ankle_p: -0.3
        r_ankle_r: 0.0

