RobotConfig:
  robot_name: "hhfc"
  type: "mujoco"
  joint_size: 14
  motor_size: 14
  joint_names: &joint_names
    - "l_hip_p"
    - "l_hip_r"
    - "l_hip_y"
    - "l_knee"
    - "l_ankle_p"
    - "l_ankle_r"
    - "r_hip_p"
    - "r_hip_r"
    - "r_hip_y"
    - "r_knee"
    - "r_ankle_p"
    - "r_ankle_r"
    - "l_shoulder_p"
    - "r_shoulder_p"
  motor_names: *joint_names

  motor_direction:
    l_hip_p: 1
    l_hip_r: 1
    l_hip_y: 1
    l_knee: 1
    l_ankle_p: 1
    l_ankle_r: 1
    r_hip_p: 1
    r_hip_r: 1
    r_hip_y: 1
    r_knee: 1
    r_ankle_p: 1
    r_ankle_r: 1
    l_shoulder_p: 1
    r_shoulder_p: 1

  observer:
    log_data: true
    log_dir: "/home/jason/bitbot-ovinf/log/extra"
    motor_pos_filter:
      # type: "None"
      type: "PassThrough"
      lower_bound: [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                    -3.14, -3.14, -3.14, -3.14, -3.14, -3.14,
                    -3.14, -3.14]
      upper_bound: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                    3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
                    3.14, 3.14] 
    motor_vel_filter:
      # type: "None"
      # type: "PassThrough"
      type: "Mean"
      history_length: 3
      lower_bound: [-50.0, -50.0, -50.0, -50.0, -50.0, -50.0,
                    -50.0, -50.0, -50.0, -50.0, -50.0, -50.0,
                    -50.0, -50.0]
      upper_bound: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0,
                    50.0, 50.0, 50.0, 50.0, 50.0, 50.0,
                    50.0, 50.0] 
    ang_vel_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    acc_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]
    euler_filter:
      # type: "None"
      type: "PassThrough"
      upper_bound: [100.0, 100.0, 100.0]
      lower_bound: [-100.0, -100.0, -100.0]

  executor:
    torque_limit:  # Nm
      l_hip_p: 200.0
      l_hip_r: 200.0
      l_hip_y: 200.0
      l_knee: 200.0
      l_ankle_p: 200.0
      l_ankle_r: 200.0
      r_hip_p: 200.0
      r_hip_r: 200.0
      r_hip_y: 200.0
      r_knee: 200.0
      r_ankle_p: 200.0
      r_ankle_r: 200.0
      l_shoulder_p: 200.0
      r_shoulder_p: 200.0
    motor_upper_limit:  # rad
      l_hip_p: 3.14
      l_hip_r: 3.14 
      l_hip_y: 3.14 
      l_knee: 3.14 
      l_ankle_p: 3.14 
      l_ankle_r:  3.14
      r_hip_p: 3.14
      r_hip_r: 3.14
      r_hip_y: 3.14
      r_knee: 3.14
      r_ankle_p: 3.14
      r_ankle_r: 3.14
      l_shoulder_p: 3.14
      r_shoulder_p: 3.14
    motor_lower_limit:  # rad
      l_hip_p: -3.14
      l_hip_r: -3.14
      l_hip_y: -3.14
      l_knee: -3.14
      l_ankle_p: -3.14
      l_ankle_r: -3.14
      r_hip_p: -3.14
      r_hip_r: -3.14
      r_hip_y: -3.14
      r_knee: -3.14
      r_ankle_p: -3.14
      r_ankle_r: -3.14
      l_shoulder_p: -3.14
      r_shoulder_p: -3.14

  init_pos:
    duration: 1.5
    init_position: &defult_init_pos
      l_hip_p: 0.3
      l_hip_r: 0.0
      l_hip_y: 0.0
      l_knee: -0.6
      l_ankle_p: -0.3
      l_ankle_r: 0.0
      r_hip_p: 0.3
      r_hip_r: 0.0
      r_hip_y: 0.0
      r_knee: -0.6
      r_ankle_p: -0.3
      r_ankle_r: 0.0
      l_shoulder_p: 0.0
      r_shoulder_p: 0.0

    p_gains: &default_p_gains
      l_hip_p: 150.0
      l_hip_r: 150.0
      l_hip_y: 100.0
      l_knee: 150.0
      l_ankle_p: 30.0
      l_ankle_r: 30.0
      r_hip_p: 150.0
      r_hip_r: 150.0
      r_hip_y: 100.0
      r_knee: 150.0
      r_ankle_p: 30.0
      r_ankle_r: 30.0
      l_shoulder_p: 100.0
      r_shoulder_p: 100.0

    d_gains: &default_d_gains
      l_hip_p: 1.5
      l_hip_r: 1.5
      l_hip_y: 1.0
      l_knee: 1.5
      l_ankle_p: 1.0
      l_ankle_r: 1.0
      r_hip_p: 1.5
      r_hip_r: 1.5
      r_hip_y: 1.0
      r_knee: 1.5
      r_ankle_p: 1.0
      r_ankle_r: 1.0
      l_shoulder_p: 1.0
      r_shoulder_p: 1.0

  zero_pos:
    duration: 1.0
    init_position: *defult_init_pos
    p_gains: *default_p_gains
    d_gains: *default_d_gains

  policy_humanoid:
    p_gains: *default_p_gains
    d_gains: *default_d_gains
    decimation: 10

    inference:
      # # Humanoid-gym based walking
      # policy_type: "Humanoid"
      # model_path: "/home/jason/bitbot-ovinf/checkpoint/hhfc/apr28_11.onnx"
      # obs_buffer_size: 15

      # Humanoid-gym based walking-standing
      # policy_type: "HumanoidStand"
      # stand_threshold: 0.045
      # model_path: "/home/jason/bitbot-ovinf/checkpoint/hhfc/apr23_22_stand.onnx"
      # obs_buffer_size: 15

      # Agi-gym DH based walking-standing
      # policy_type: "HumanoidStand"
      # stand_threshold: 0.045
      # model_path: "/home/jason/bitbot-ovinf/checkpoint/hhfc/dh.onnx"
      # obs_buffer_size: 66

      # lupinjia humanoid walk
      policy_type: "HumanoidWalk"
      model_path: "/home/jason/bitbot-ovinf/checkpoint/hhfc/May28_23-40-17_4000.onnx"
      obs_buffer_size: 5

      log_data: true
      log_dir: "/home/jason/bitbot-ovinf/log/policy"

      device: "CPU"
      single_obs_size: 49
      action_size: 12
      action_scale: 0.25
      obs_scales:
        ang_vel: 0.25
        lin_vel: 2.0
        command: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        proj_gravity: 1.0
      clip_action: 100.0
      realtime: true # false
      gait_period: 0.8
      theta_left: 0.5
      theta_right: 0.0
      swing_phase_ratio: 0.4
      stance_phase_ratio: 0.6
      control_dt: 0.01        # 100Hz

      policy_joint_names:
        - "l_hip_p"
        - "l_hip_r"
        - "l_hip_y"
        - "l_knee"
        - "l_ankle_p"
        - "l_ankle_r"
        - "r_hip_p"
        - "r_hip_r"
        - "r_hip_y"
        - "r_knee"
        - "r_ankle_p"
        - "r_ankle_r"

      policy_default_position:
        l_hip_p: 0.3
        l_hip_r: 0.0
        l_hip_y: 0.0
        l_knee: -0.6
        l_ankle_p: -0.3
        l_ankle_r: 0.0
        r_hip_p: 0.3
        r_hip_r: 0.0
        r_hip_y: 0.0
        r_knee: -0.6
        r_ankle_p: -0.3
        r_ankle_r: 0.0

